### ISSUE TITLE
Beginning of every chapter trimmed above first link

### ISSUE THREAD

**Issue by mruwek** [dumbledore/AlbiteREADER#189]
I have some books with lots of links (notes) and Albite Reader does not display in them text above first link in every chapter.

Example:
— Original text with link: Quick brown fox _[link]_ jumped over the lazy dog.
— Albite reader displays: jumped over the lazy dog.

Example book connected with this issue:
Henryk Sienkiewicz „Ogniem i Mieczem” (pl): http://www.wolnelektury.pl/media/lektura/ogniem-i-mieczem.epub

**Comment by dumbledore** [comment]
Thanks :-) I'll look into it.

**Comment by dumbledore** [comment]
Turns out it wasn't the links, but the <!DOCTYPE> declaration. I'm fixing it now.

**Comment by dumbledore** [comment]
You won't believe how stupid I may sometimes be :-D

**Comment by dumbledore** [comment]
I had forgotten a return in an if clause. :-D. It's working now.
