### ISSUE TITLE
Failing to open epub (opens ok in Adobe Digital Editions)

### ISSUE THREAD

**Issue by wryun** [dumbledore/AlbiteREADER#190]
Tried a couple, neither work. e.g.:

http://baencd.thefifthimperium.com/22-MissionofHonorCD/MissionofHonorCD/Empire%20From%20the%20Ashes/Empire_from_the_Ashes.epub

It says 'Sorry, cannot open this book." But no other error message; and I have said 'yes' in the permissions...

**Comment by dumbledore** [comment]
On the Nokia emulator I can open the book, but I get OutOfMemoryError for the chapters. Seems there's something funny going on. Could I ask which phone do you have?

**Comment by dumbledore** [comment]
It seems the <script .../> element brakes something.

**Comment by wryun** [comment]
Sorry, I didn't investigate it carefully enough before rashly posting the issue - it doesn't seem to open anything, even .txt files. Presumably something to do with file access, though other apps have worked.

I'm using a 'Sciphone i9' (very cheap Chinese iphone clone, with terrible built-in fonts...).

**Comment by dumbledore** [comment]
Well, well. Looks like a nice iPhone, though it's seems a bit limited. There are two ideas I have:
1. Try moving the books around, i.e. try to open them from another folder
2. Try using Albite Light or Tiny, because the device may have very limited heap memory

**Comment by wryun** [comment]
Thanks, already tried those sadly (Light/Tiny and diff locations - it claims 1.5mb of heap)... if I get some time I'll try to work out how to set up the compilation myself and narrow down what's happening. One odd thing that seems to go on with this phone is that other apps somehow turn 'Memory Card:/folder' locations into 'E:/folder' locations. Also, Albite seems to lower-case the locations when it tries to access them (but maybe I'm misremembering what other apps have done).

**Comment by moronigranja** [comment]
I'm having the same problem on a LG KP500 (Cookie). I have tried two epub books I created myself using calibre. They open fine on android's FBReaderJ and Aldiko. What additional info should I send you about it?

**Comment by moronigranja** [comment]
I'll try changing locations and try opening a txt file as well. Just so you know, I don't get the option to "allow always" for permissions...

**Comment by dumbledore** [comment]
I'm really sorry, I can't help you at the moment as I'm terribly busy. Good luck with the app and I'll write back as soon as I'm free to examine it more closely.

**Comment by dumbledore** [comment]
This was an issue with non-lowercase filenames on linux phones. Fixed in 2.0.14
