### ISSUE TITLE
After the end of the italic text is a superfluous space

### ISSUE THREAD

**Issue by SaGa59** [dumbledore/AlbiteREADER#191]
Sorry for poor english, but I'm "read only" in this language.

When I read a book with some words in italics, the Albite reader insert after the italic characters one superfluous space.

The text in the epub is:  This is an <i>Italic</i>ised text
In  the Albite Reader:     This is an italic ised text.

Other issue:

I read in hungarian, In this language is "ő" character (&#337;). If in the text is "őn", in the screen of the Albite reader is only "ő". The "n" fade away. The "ő" with other character is OK, and the "n" is too, but in this combination (őn) the "n" always disapear.

I use th Albite reader 2.012 in Nokia 5800 XM...

SaGa

**Comment by dumbledore** [comment]
Thanks, SaGa59.
1. I can't do anything about the Italics. It's a known limitation. It'll be fixed in _Albite3_.
2. It's a very odd issue you are describing there. Could you provide and epub that produces this kind of behaviour?

Thanks for trying Albite! :-)

**Comment by SaGa59** [comment]
Thank You!

2: Sorry, this is my trouble, not an issue in the Albite reader.
I proof-read the books in the mobile phone, bookmark the errors and revise the source of the books in PC, with Libre Office.

I found many errors in one e-pub with this symptom, but not found errors in the odt (source of the epub).

Now I search the epub for the send for You, and found the two versions of the source (odt). In the older version are this errors without repairing, but in the other version this errors are repaired (eight monts ago, and I forgot this), and I was read the revised version, when I search the errors.

Sorry for fake issue reporting and thank you for the Albite Reader...
