### ISSUE TITLE
epub containing ncx won't render?

### ISSUE THREAD

**Issue by bkzland** [dumbledore/AlbiteREADER#192]
I've run into an epub that didn't render in Albite (displayed just one chapter with the text */, and nothing more). After removing the toc.ncx from the epub without modifying anything else Albite rendered it just fine.
Not sure how to investigate further

Albite version 2.0.1.4 HD, running on a Sony w890i. Not sure how to investigate further, I can provide the epub on request.

**Comment by dumbledore** [comment]
Hi Gouken and thank you for bothering to open up an issue! The behaviour you are getting there is quite unusual especially for the fact that _Albite doesn't use the toc.ncx file_. I'd like to see that epub if I may. :-)

**Comment by bkzland** [comment]
After retrying my initial solution I am finding that removing the toc.ncx file does not actually repeat the success, in fact it does nothing.
I may have done something else through Calibre that I forgot to note in order to have Albite render this particular epub file, i.e. convert from epub to epub with Calibre's default options.

This is the non-working epub in question: http://96.8.113.43/jatfltbi.epub (just showing 1 chapter containing */)

From what I can see the version Calibre's convert produces has its folder structed altered, also some information in the header appear changed. http://96.8.113.43/jatfltbi_calibre.epub (works fine).

I'm still not sure what exaclty causes the error, maybe it's something in the original epub that breaks a standard. Hope this helps to find the actual cause.

**Comment by dumbledore** [comment]
Thanks, Gouken. I've downloaded the epubs. I'll look at them in more detail this or next weekend as I'm really busy at work. Thanks you very much for contacting me. :-)

**Comment by dumbledore** [comment]
This is because the hrefs in the OPF file are encoded, like so:

> "Text/Joe%20Abercrombie%20-%20%5BThe%20First%20Law%2001%5D%20-%20The%20Blade%20Itself%20%28v1.0%29_split_001.html

But the files in the ZIP (i.e. the EPUB) are already decoded:

> OEBPS\Text\Joe Abercrombie - [The First Law 01] - The Blade Itself (v1.0)_split_001.html
