### ISSUE TITLE
Option to disable screen rotation on HD version

### ISSUE THREAD

**Issue by kazuoteramoto** [dumbledore/AlbiteREADER#201]
My phone have a somewhat too much sensible accelerometer (but only when not needed) and when screen changes orientation its flash a white screen that make me blind when reading with lights off at my bed. And when I'm laying down on my  bed I constantly change positions so I constantly get blind with a rotated screen =[.

If this change don't introduce to much code and be easy enough to implement, can I ask for it? I'm using the AlbiteReader HD version 2.2. 

Or what about a option to lock the current orientation? But I think this is will introduce too much interface changes.

Thanks,
Kazuo

PS. AlbiteREADER is the most awesome program I have on my phone. I can't thank enough for the work done on it.

**Comment by dumbledore** [comment]
Have you got a Nokia device by some chance? If so, it can be easily remedied.

As to the white background, you've got a point, sry. Can't cope with all the details, there's just too little time. :/

**Comment by kazuoteramoto** [comment]
Yes a Nokia 5530.

And forget about the white background, with this device I'm happy that it don't explode =].

**Comment by dumbledore** [comment]
Haha. Well, if it _exploded_ I would've worried indeed. You know, I've done a lot of testing in the period of six months. This is confirmed by the fact that this is issue #201. :-)

As to the accelerometer thingy. Generally, Albite does _not_ support autorotation, this is Symbian's doing. What it does is, it just notifies the app that the screen size changed. Therefore, there's no way to disable autorotation from _within_ Albite, i.e. to do it interactively. The only way is to change an attribute in the app's manifest and do it _once and for all_. I'm not sure if that would be OK for you, as it would completely disable the accelerometer for Albite, but at the very least, Albite supports screen rotation from the menus (main menu -> Screen mode). If it's OK, read on.

If you're geeky enough to use GitHub and write in Python, I bet you can do it with just little help on my side. First of all, you might not know it, but .jars are actually a .ZIP file with a manifest. So what you should do is:
1. Unzip AlbiteReaderHD-2.2.jar
2. Open META-INF/MANIFEST.MF in a text editor
3. Add this line to the file and save: `Nokia-MIDlet-App-Orientation: portrait`.
4. Zip again and change the extension to .jar
5. Done.

P.S. Have you looked at my other project: [AnkSteer](http://svetlin.posterous.com/flypad-beta), a.k.a. Flypad?

**Comment by dumbledore** [comment]
Forgot to ask you. Are you by any chance Japanese? I hope I'm not being impertinent, but I'm curious, you know :))

**Comment by kazuoteramoto** [comment]
> I'm not sure if that would be OK for you, as it would completely disable the accelerometer for Albite
> [...]
> So what you should do is

Done. Perfect, its ok for me, as this is exactly what I needed. Issue closed.

> P.S. Have you looked at my other project: AnkSteer, a.k.a. Flypad?

Yes I have, and I found it genial. But I'm not playing too much lately =[.

> Are you by any chance Japanese?

Not really, I'm Brazilian but my mother family is Japanese.
