### ISSUE TITLE
.ALX not saving.

### ISSUE THREAD

**Issue by Madcat75** [dumbledore/AlbiteREADER#202]
I have Albite Reader on a Samsung GT-B3410, the program runs fine when I exit it creates a .ALX file but the file is empty and it does not save my progress, I have given read and write permissions but nothing seems to work.

**Comment by dumbledore** [comment]
Am sad to hear that mate. I'm not sure what the problem might be, but it sounds like even though you're giving Albite write permissions, for some reason the JVM is not really doing that.

Perhaps, if you try putting your books somewhere else? On an SD card for example (if not done this already)?

And, do you exit the app from the main menu, not by using the red phone button.

Cheers!

**Comment by Madcat75** [comment]
Ok have managed to fix it, for some reason when I had my books on my SD card it was not saving the data, when I put the files onto my phone memory it saved the data perfectly.

**Comment by dumbledore** [comment]
Glad you found a solution. Cheers!
