### ISSUE TITLE
build error: package java.nio does not exist

### ISSUE THREAD

**Issue by coax75ohm** [dumbledore/AlbiteREADER#208]
I trying to stumble through how to build this project, since there is no documentation on the process. From what I've been able to gather it requires NetBeans, I'm using the full version of 6.9.1 (7.3 didn't recognize it as a valid project). But I'm currently getting the following errors and from the searching I've done it seems that java.nio isn't implemented for J2ME.

```
Compiling 118 source files to /Users/coax/build/AlbiteREADER/build/NormalNoTouchExport/compiled
/Users/coax/build/AlbiteREADER/src/gnu/zip/ZipFile.java:47: package java.nio does not exist
import java.nio.ByteBuffer;
/Users/coax/build/AlbiteREADER/src/gnu/zip/ZipFile.java:737: cannot find symbol
symbol  : class ByteBuffer
location: class gnu.zip.ZipFile.PartialInputStream
          ByteBuffer bufferBuffer = ByteBuffer.wrap(buffer, pos, length);
/Users/coax/build/AlbiteREADER/src/gnu/zip/ZipFile.java:737: cannot find symbol
symbol  : variable ByteBuffer
location: class gnu.zip.ZipFile.PartialInputStream
          ByteBuffer bufferBuffer = ByteBuffer.wrap(buffer, pos, length);
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
```

How did you resolve this dependency?

**Comment by coax75ohm** [comment]
After further research it seems that the issue is lack of support for JSR-239 on OS X (and Solaris, which would be my second choice). So I installed the JDK and NetBeans on a Linux VM and was then able to build successfully.

**Comment by dumbledore** [comment]
Glad you found a solution. :-)
